# Generated by Django 4.0.3 on 2022-03-24 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeolocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('continent_code', models.CharField(blank=True, max_length=3, null=True)),
                ('continent_name', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('country_name', models.CharField(blank=True, max_length=50, null=True)),
                ('region_code', models.CharField(blank=True, max_length=3, null=True)),
                ('region_name', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=50, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
