# Generated by Django 4.0.3 on 2022-03-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_geolocationdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocationdata',
            name='is_own',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='continent_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='continent_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='country_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='country_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='ip',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='latitude',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='longitude',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='region_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='region_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
