# Generated by Django 4.0.3 on 2022-03-26 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_geolocationdata_is_own_alter_geolocationdata_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocationdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geolocation', to=settings.AUTH_USER_MODEL),
        ),
    ]
