# Generated by Django 4.0.3 on 2022-03-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_geolocationdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocationdata',
            name='latitude',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='geolocationdata',
            name='longitude',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
